-- =====================================================================
-- Bookly database schema (Supabase / PostgreSQL)
--
-- Run this file ONCE in the SQL Editor of a new, empty Supabase project.
-- Order: tables -> helper functions -> trigger -> indexes -> RLS policies.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------

-- id is "by default" (not "always") so the seed script can insert fixed ids.
create table public.books (
  id           bigint generated by default as identity primary key,
  title        text    not null,
  author       text    not null,
  price        numeric not null check (price >= 0),
  cover        text,
  category     text    not null,
  release_date date,
  description  text
);

-- One profile per auth user. Created automatically by a trigger (see 3.).
create table public.profiles (
  id        uuid primary key references auth.users (id) on delete cascade,
  firstname text,
  lastname  text,
  street    text,
  zip       text,
  city      text,
  country   text,
  role      text not null default 'user' check (role in ('user', 'admin'))
);

-- user_id may be NULL so that demo reviews can be seeded without an account.
-- Unique per book and user: one review per user and book.
create table public.reviews (
  id         bigint generated always as identity primary key,
  book_id    bigint not null references public.books (id) on delete cascade,
  user_id    uuid references auth.users (id) on delete cascade,
  user_name  text   not null,
  rating     integer not null check (rating between 1 and 5),
  text       text,
  created_at timestamptz not null default now(),
  unique (book_id, user_id)
);

create table public.delivery_addresses (
  id        bigint generated always as identity primary key,
  user_id   uuid not null references auth.users (id) on delete cascade,
  firstname text not null,
  lastname  text not null,
  street    text not null,
  zip       text not null,
  city      text not null,
  country   text not null
);

create table public.orders (
  id             bigint generated always as identity primary key,
  user_id        uuid not null references auth.users (id) on delete cascade,
  total_price    numeric not null check (total_price >= 0),
  order_date     timestamptz not null default now(),
  delivered_date timestamptz,
  status         text not null default 'processing'
                 check (status in ('processing', 'shipped', 'delivered'))
);

-- title, author and price are copied from the book at order time,
-- so old orders stay correct even if a book changes or is removed.
create table public.order_items (
  id       bigint generated always as identity primary key,
  order_id bigint  not null references public.orders (id) on delete cascade,
  book_id  bigint  references public.books (id) on delete set null,
  price    numeric not null check (price >= 0),
  quantity integer not null default 1 check (quantity > 0),
  title    text,
  author   text
);


-- ---------------------------------------------------------------------
-- 2. Helper functions
-- ---------------------------------------------------------------------

-- True if the current user is an admin. SECURITY DEFINER avoids an
-- endless RLS loop when policies on "profiles" call it.
create function public.is_admin()
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Moves the id counter of "books" behind the highest existing id. Needed after
-- seeding books with fixed ids, otherwise new books would get duplicate ids.
-- Only callable with the service_role key (used by scripts/seed-books.ts).
create function public.sync_books_id_seq()
returns void
language sql security definer set search_path = ''
as $$
  select setval(
    pg_get_serial_sequence('public.books', 'id'),
    coalesce((select max(id) + 1 from public.books), 1),
    false
  );
$$;

revoke execute on function public.sync_books_id_seq() from public, anon, authenticated;

-- Lets a logged-in user delete their own account. All related data
-- (profile, addresses, reviews, orders) is removed via ON DELETE CASCADE.
-- Call from the frontend with: supabase.rpc('delete_own_account')
create function public.delete_own_account()
returns void
language sql security definer set search_path = ''
as $$
  delete from auth.users where id = auth.uid();
$$;

revoke execute on function public.delete_own_account() from public, anon;
grant  execute on function public.delete_own_account() to authenticated;


-- ---------------------------------------------------------------------
-- 3. Trigger: create a profile when a user registers
-- ---------------------------------------------------------------------

-- Reads firstname/lastname from the sign-up metadata, if provided:
-- supabase.auth.signUp({ email, password, options: { data: { firstname, lastname } } })
create function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, firstname, lastname)
  values (
    new.id,
    new.raw_user_meta_data ->> 'firstname',
    new.raw_user_meta_data ->> 'lastname'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ---------------------------------------------------------------------
-- 4. Indexes (foreign keys are not indexed automatically in PostgreSQL)
-- ---------------------------------------------------------------------

create index books_category_idx       on public.books (category);
create index reviews_user_id_idx      on public.reviews (user_id);
create index delivery_user_id_idx     on public.delivery_addresses (user_id);
create index orders_user_id_idx       on public.orders (user_id);
create index order_items_order_id_idx on public.order_items (order_id);
-- reviews (book_id, user_id) is already covered by the UNIQUE constraint.


-- ---------------------------------------------------------------------
-- 5. Row Level Security
-- ---------------------------------------------------------------------

alter table public.books              enable row level security;
alter table public.profiles           enable row level security;
alter table public.reviews            enable row level security;
alter table public.delivery_addresses enable row level security;
alter table public.orders             enable row level security;
alter table public.order_items        enable row level security;

-- Books: visible to everyone, only admins may change them.
create policy "books: read all" on public.books
  for select using (true);
create policy "books: admin write" on public.books
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Profiles: users see and edit only their own profile, admins see all.
create policy "profiles: read own or admin" on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.is_admin());
create policy "profiles: insert own" on public.profiles
  for insert to authenticated
  with check (id = auth.uid());
create policy "profiles: update own or admin" on public.profiles
  for update to authenticated
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());
create policy "profiles: admin delete" on public.profiles
  for delete to authenticated
  using (public.is_admin());

-- The role column cannot be changed through the API (no user can make
-- themselves admin). Set it in the Supabase dashboard instead.
revoke insert, update on public.profiles from anon, authenticated;
grant insert (id, firstname, lastname, street, zip, city, country)
  on public.profiles to authenticated;
grant update (firstname, lastname, street, zip, city, country)
  on public.profiles to authenticated;

-- Reviews: readable by everyone, writable only by their author.
create policy "reviews: read all" on public.reviews
  for select using (true);
create policy "reviews: insert own" on public.reviews
  for insert to authenticated
  with check (user_id = auth.uid());
create policy "reviews: update own" on public.reviews
  for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "reviews: delete own or admin" on public.reviews
  for delete to authenticated
  using (user_id = auth.uid() or public.is_admin());

-- Delivery addresses: own addresses only, admins may manage all.
create policy "addresses: own or admin" on public.delivery_addresses
  for all to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check (user_id = auth.uid() or public.is_admin());

-- Orders: users read and create their own orders (always as 'processing').
-- Only admins can change the status (processing -> shipped -> delivered).
create policy "orders: read own or admin" on public.orders
  for select to authenticated
  using (user_id = auth.uid() or public.is_admin());
create policy "orders: insert own" on public.orders
  for insert to authenticated
  with check (
    user_id = auth.uid()
    and status = 'processing'
    and delivered_date is null
  );
create policy "orders: admin update" on public.orders
  for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy "orders: admin delete" on public.orders
  for delete to authenticated
  using (public.is_admin());

-- Order items: follow the rules of their order.
create policy "order_items: read own or admin" on public.order_items
  for select to authenticated
  using (exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and (o.user_id = auth.uid() or public.is_admin())
  ));
create policy "order_items: insert into own new order" on public.order_items
  for insert to authenticated
  with check (exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and o.user_id = auth.uid()
      and o.status = 'processing'
  ));
create policy "order_items: admin update" on public.order_items
  for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy "order_items: admin delete" on public.order_items
  for delete to authenticated
  using (public.is_admin());